# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version=1.3.13
maven_group=com.seailz
archives_base_name=coreshader-devtools


minecraft_version=26.3-snapshot-10
minecraft_depends=26.3-alpha.10
loader_version=0.19.3
loom_version=1.15.5

# Fabric API modules
fabric_api_base_version=2.0.5+3434d6d986
fabric_key_mapping_version=2.0.7+3434d6d986
fabric_screen_api_version=5.2.1+3434d6d986
